### ISSUE TITLE
part 3 functions at runtime callback 3.8.3 error

### ISSUE THREAD

**Issue by Calexxxxx** [udacity/fend-issues#152]
Hi,

The quiz about `.map()` returns an error on submitting.
This was pointed out to me by another student.
I remember passing the quiz successfully now with helping him out I tried to resubmit my own quiz.

Link to the quiz
https://classroom.udacity.com/nanodegrees/nd001/parts/4942f4d7-a48d-4794-9eb0-404b3ed3cfe1/modules/7e56389b-50d8-4e3a-84a0-eb3fd45456b2/lessons/fd2e70b8-84b4-4793-a89e-78a695ecf89d/concepts/435a5d87-0a67-4787-9096-5426e36f9a90

The quiz itself
```
/* Using map()
 *
 * Using the musicData array and map():
 *   - Return a string for each item in the array in the following format:
 *     <album-name> by <artist> sold <sales> copies
 *   - Store the returned data in a new albumSalesStrings variable
 *
 * Note:
 *   - Do not delete the musicData variable
 *   - Do not alter any of the musicData content
 *   - Do not format the sales number; leave it as a long string of digits
 */

const musicData = [
    { artist: 'Adele', name: '25', sales: 1731000 },
    { artist: 'Drake', name: 'Views', sales: 1608000 },
    { artist: 'Beyonce', name: 'Lemonade', sales: 1554000 },
    { artist: 'Chris Stapleton', name: 'Traveller', sales: 1085000 },
    { artist: 'Pentatonix', name: 'A Pentatonix Christmas', sales: 904000 },
    { artist: 'Original Broadway Cast Recording', 
      name: 'Hamilton: An American Musical', sales: 820000 },
    { artist: 'Twenty One Pilots', name: 'Blurryface', sales: 738000 },
    { artist: 'Prince', name: 'The Very Best of Prince', sales: 668000 },
    { artist: 'Rihanna', name: 'Anti', sales: 603000 },
    { artist: 'Justin Bieber', name: 'Purpose', sales: 554000 }
];

const albumSalesStrings = musicData.map(function(data) {
  return `${data.name} by ${data.artist} sold ${data.sales} copies`;
});

console.log(albumSalesStrings);
```

The test run outcome 
```
[ '25 by Adele sold 1731000 copies',
  'Views by Drake sold 1608000 copies',
  'Lemonade by Beyonce sold 1554000 copies',
  'Traveller by Chris Stapleton sold 1085000 copies',
  'A Pentatonix Christmas by Pentatonix sold 904000 copies',
  'Hamilton: An American Musical by Original Broadway Cast Recording sold 820000 copies',
  'Blurryface by Twenty One Pilots sold 738000 copies',
  'The Very Best of Prince by Prince sold 668000 copies',
  'Anti by Rihanna sold 603000 copies',
  'Purpose by Justin Bieber sold 554000 copies' ]
```

The error
```
Traceback (most recent call last):
  File "falcon.py", line 96, in <module>
    sys.stdout.write(formatter.format_results_as_json_string(mode_idx, stack_module.submit_files(), args.show_pretty_submit, stack_module.transform))
  File "/tmp/vmuser_kvzqjealyf/falcon/formatter.py", line 62, in format_results_as_json_string
    results[files.RESULTS_OUT] = transformer(util.get_file_contents(files.RESULTS_OUT))
  File "falcon/stack/js_mocha.py", line 167, in transform
    grading_response = json.loads(eval_output)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I also tried the quiz with es6 syntax and the error is the same

```
const albumSalesStrings = musicData.map(data => return `${data.name} by ${data.artist} sold ${data.sales} copies`);
```

**Update** 

After talking to a student mentor that suggested the concatenation of the output I tested it.

```
const albumSalesStrings = musicData.map(function(data) {
  return data.name + ' by ' + data.artist + ' sold ' + data.sales + ' copies';
});
```
The error on submitting is still the same.

**Comment by Calexxxxx** [comment]
Sorry, I now see on GitHub there is a related issue #149. I posted my issue over waffle and didn't realize it was about the same quiz.

**Comment by forbiddenvoid** [comment]
Fixed. This quiz should work correctly now.
